[project]
name = "fastapi-data-analysis-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "pandas-stubs==2.3.2.250827",
    "python-multipart>=0.0.20",
]
